### ISSUE TITLE
extend the paint canvas size

### ISSUE THREAD

**Issue by LinkunGao** [LinkunGao/copper3d_visualisation#8]
Issue: 
Current, the slice canvas width and height are fixed. 

so, we need to find a solution to extend canvas size.

**Comment by LinkunGao** [comment]
solution1:

we can increase drawing canvas size based on slice canvas size and times our magnifying power.
when we draw it on the slice canvas we need to decrease the drawing canvas size to the same as the origin canvas size.

**Comment by Mingyang-Li** [comment]
Cool project - happy to collab building new features here and there if you need help, just let me know:) @LinkunGao
